input:
  equipment: equipment.xlsx
  tasks: tasks.xlsx
  setups: setups.xlsx

output:
  daily_tasks: result_1.xlsx
  final_setups: setups_1.xlsx
  tasks_left: tasks_1.xlsx

rules:
  human_labor_limit: 12
  machine_labor_limit: 11